#=========Spring boot application=========
spring:
  application:
    name: cableMonitor

server:
  port: 3000

mihile:
  # 请求 /stream/play的间隔，超过则关闭流
  interval: 60000
  ffmpegpath: D:/work/ffmpeg/bin/


